services:
  - type: web
    plan: free
    name: quizzical
    runtime: python
    repo: https://github.com/ipbrennan90/quizzical.git
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m gunicorn run:app --workers 1 --threads 8"
    envVars:
      - key: DATABASE_URL # Sets DATABASE_URL to the connection string of the django-app-db database
        fromDatabase:
          name: quizzical-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: quizzical-redis
          property: connectionString
  - type: redis
    name: quizzical-redis
    ipAllowList: []

databases:
  - name: quizzical-db
    plan: free
